-- All fixture accounts, Vault entries, events and notifications roll back. No external requests.
begin;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); denied uuid:=gen_random_uuid(); eid uuid:=gen_random_uuid();
 role_id uuid:=gen_random_uuid(); denied_role uuid:=gen_random_uuid(); client_id uuid:=gen_random_uuid(); state text; pending jsonb; lease jsonb; scope jsonb; job jsonb; old_revision bigint; original_id text; total integer;
begin
 insert into public.duuk_roles(id,name) values(role_id,'Teste '||role_id),(denied_role,'Teste '||denied_role);
 insert into public.duuk_role_permissions(role_id,permission,allowed) select role_id,k.key,true from public.duuk_permission_keys k where k.key in ('agenda','site','crm','crm.clients','crm.pipeline','crm.activities','crm.followups');
 insert into auth.users(id,email) values(a,a||'@test.invalid'),(b,b||'@test.invalid'),(denied,denied||'@test.invalid');
 insert into public.duuk_profiles(id,name,email,role_id) values(a,'Teste calendário A',a||'@test.invalid',role_id),(b,'Teste calendário B',b||'@test.invalid',role_id),(denied,'Teste sem agenda',denied||'@test.invalid',denied_role);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 insert into public.duuk_events(id,title,start_date,end_date,created_by,responsible_id) values(eid,'Evento isolado de teste',current_date+30,current_date+30,a,b);
 if not exists(select 1 from public.duuk_notifications where user_id=b and dedupe_key='agenda:assigned:'||eid||':1') then raise exception 'Assignment notification missing';end if;
 if exists(select 1 from public.duuk_notifications where user_id=denied and dedupe_key like '%'||eid||'%') then raise exception 'Agenda permission leaked';end if;
 -- A different logged-in member cannot consume the OAuth state or replay it.
 state:='calendar-test-'||a;
 perform public.duuk_calendar_backend('start',jsonb_build_object('user_id',a,'state_hash',state,'verifier','test-verifier'));
 begin perform public.duuk_calendar_backend('consume',jsonb_build_object('user_id',b,'state_hash',state));raise exception 'State crossed accounts';exception when sqlstate 'PT400' then null;end;
 pending:=public.duuk_calendar_backend('consume',jsonb_build_object('user_id',a,'state_hash',state));
 begin perform public.duuk_calendar_backend('consume',jsonb_build_object('user_id',a,'state_hash',state));raise exception 'State replay accepted';exception when sqlstate 'PT400' then null;end;
 perform public.duuk_calendar_backend('connect',jsonb_build_object('user_id',a,'state_hash',state,'google_subject','test-sub-a','account_email','a@test.invalid','calendar_id','test-calendar-a','tokens',jsonb_build_object('access_token','FAKE_TEST_TOKEN','refresh_token','FAKE_TEST_REFRESH')));
 state:='calendar-test-'||b;
 perform public.duuk_calendar_backend('start',jsonb_build_object('user_id',b,'state_hash',state,'verifier','test-verifier'));
 perform public.duuk_calendar_backend('consume',jsonb_build_object('user_id',b,'state_hash',state));
 perform public.duuk_calendar_backend('connect',jsonb_build_object('user_id',b,'state_hash',state,'google_subject','test-sub-b','account_email','b@test.invalid','calendar_id','test-calendar-b','tokens',jsonb_build_object('access_token','FAKE_TEST_TOKEN','refresh_token','FAKE_TEST_REFRESH')));
 select count(*) into total from public.duuk_calendar_sync where user_id in(a,b) and event_id=eid;
 if total<>2 then raise exception 'Future event backfill missing for multiple accounts';end if;
 if exists(select 1 from public.duuk_calendar_connections c join vault.secrets v on v.id=c.credential_id where c.user_id in(a,b) and v.secret like '%FAKE_TEST_TOKEN%') then raise exception 'Vault storage is not encrypted';end if;
 if (public.duuk_calendar_backend('status',jsonb_build_object('user_id',a)))::text like '%FAKE_TEST%' then raise exception 'Status exposed token';end if;
 begin perform public.duuk_calendar_backend('start',jsonb_build_object('user_id',denied,'state_hash','denied','verifier','x'));raise exception 'Permissionless OAuth allowed';exception when sqlstate 'PT403' then null;end;
 lease:=public.duuk_calendar_backend('claim',jsonb_build_object('user_id',a));
 scope:=jsonb_build_object('user_id',a,'generation',lease->>'generation','lease_id',lease->>'lease_id');
 if public.duuk_calendar_backend('claim',jsonb_build_object('user_id',a)) is not null then raise exception 'Concurrent worker acquired same account';end if;
 select to_jsonb(j) into job from public.duuk_calendar_sync j where user_id=a and event_id=eid;
 old_revision:=(job->>'revision')::bigint;original_id:=job->>'google_event_id';
 update public.duuk_events set title='Evento editado no teste' where id=eid;
 perform public.duuk_calendar_backend('finish',scope||jsonb_build_object('event_id',eid,'revision',old_revision));
 if (select status from public.duuk_calendar_sync where user_id=a and event_id=eid)<>'pending' then raise exception 'Stale acknowledgement erased newer job';end if;
 if (select google_event_id from public.duuk_calendar_sync where user_id=a and event_id=eid)<>original_id then raise exception 'Update changed persistent ID';end if;
 -- Permission blocks stop workers but retain changes for a later authorized export.
 select revision into old_revision from public.duuk_calendar_sync where user_id=b and event_id=eid;
 update public.duuk_profiles set role_id=denied_role where id=b;
 if public.duuk_calendar_backend('claim',jsonb_build_object('user_id',b)) is not null then raise exception 'Permissionless worker acquired account';end if;
 update public.duuk_events set title='Alterado durante bloqueio de acesso' where id=eid;
 if (select revision from public.duuk_calendar_sync where user_id=b and event_id=eid)<=old_revision then raise exception 'Permission block lost a source change';end if;
 update public.duuk_profiles set role_id=(select p.role_id from public.duuk_profiles p where p.id=a) where id=b;
 select to_jsonb(j) into job from public.duuk_calendar_sync j where user_id=a and event_id=eid;
 perform public.duuk_calendar_backend('finish',scope||jsonb_build_object('event_id',eid,'revision',job->>'revision','error','Falha de teste'));
 if not exists(select 1 from public.duuk_calendar_sync where user_id=a and event_id=eid and status='error' and attempts=1 and next_attempt_at>now()) then raise exception 'Retry backoff missing';end if;
 -- Disconnect invalidates an in-flight worker, deletes credentials, keeps DUUK source and Google mappings.
 perform public.duuk_calendar_backend('disconnect',jsonb_build_object('user_id',a));
 begin perform public.duuk_calendar_backend('jobs',scope);raise exception 'Disconnected worker still authorized';exception when sqlstate 'PT409' then null;end;
 if not exists(select 1 from public.duuk_events where id=eid) then raise exception 'Disconnect removed source event';end if;
 if (select credential_id from public.duuk_calendar_connections where user_id=a) is not null then raise exception 'Disconnect retained credentials';end if;
 update public.duuk_events set status='cancelled' where id=eid;
 if not exists(select 1 from public.duuk_notifications where user_id=b and title='Compromisso cancelado' and dedupe_key like '%'||eid||'%') then raise exception 'Cancellation notification missing';end if;
 delete from public.duuk_events where id=eid;
 if not exists(select 1 from public.duuk_calendar_sync where user_id=b and event_id=eid and desired_action='delete') then raise exception 'Deletion tombstone was lost';end if;
 -- Pending OAuth cannot reconnect an account after disconnect.
 state:='cancelled-flow-'||a;
 perform public.duuk_calendar_backend('start',jsonb_build_object('user_id',a,'state_hash',state,'verifier','test-verifier'));
 perform public.duuk_calendar_backend('consume',jsonb_build_object('user_id',a,'state_hash',state));
 perform public.duuk_calendar_backend('disconnect',jsonb_build_object('user_id',a));
 begin perform public.duuk_calendar_backend('connect',jsonb_build_object('user_id',a,'state_hash',state));raise exception 'Cancelled OAuth flow reconnected';exception when sqlstate 'PT409' then null;end;
 if has_table_privilege('authenticated','public.duuk_calendar_connections','SELECT') or has_table_privilege('anon','public.duuk_calendar_sync','SELECT') then raise exception 'Private integration table exposed';end if;
 if has_function_privilege('authenticated','public.duuk_calendar_backend(text,jsonb)','EXECUTE') or has_function_privilege('anon','public.duuk_admin_notice(uuid,text,text,uuid)','EXECUTE') then raise exception 'Server-only RPC exposed';end if;
 begin perform public.duuk_admin_notice(a,'Teste','Aviso de teste',gen_random_uuid());raise exception 'Non-admin notice allowed';exception when sqlstate 'PT403' then null;end;
 insert into public.duuk_clients(id,name,created_by,owner_id) values(client_id,'Cliente de teste isolado',a,b);
 update public.duuk_clients set stage='proposal' where id=client_id;
 insert into public.duuk_activities(client_id,user_id,channel,notes) values(client_id,a,'call','Contato isolado de teste');
 if not exists(select 1 from public.duuk_notifications where user_id=b and title='Novo cliente cadastrado' and dedupe_key='client:new:'||client_id) then raise exception 'Client creation notification missing';end if;
 if not exists(select 1 from public.duuk_notifications where user_id=b and title='Negociação avançou no pipeline' and dedupe_key like 'client:stage:'||client_id||'%') then raise exception 'Pipeline notification missing';end if;
 if not exists(select 1 from public.duuk_notifications where user_id=b and title='Novo contato registrado') then raise exception 'Contact notification missing';end if;
 perform duuk_private.notify_members('system',null,'Aviso isolado','Teste','/admin/notificacoes','test:dedupe:'||a,b);
 perform duuk_private.notify_members('system',null,'Aviso isolado','Teste','/admin/notificacoes','test:dedupe:'||a,b);
 if (select count(*) from public.duuk_notifications where user_id=b and dedupe_key='test:dedupe:'||a)<>1 then raise exception 'Notification duplicated';end if;
 insert into public.duuk_notification_preferences(user_id,system) values(b,false);
 perform duuk_private.notify_members('system',null,'Aviso bloqueado','Teste','/admin/notificacoes','test:muted:'||a,b);
 if exists(select 1 from public.duuk_notifications where user_id=b and dedupe_key='test:muted:'||a) then raise exception 'Category preference ignored';end if;
 update public.duuk_profiles set is_super_admin=true where id=a;
 perform public.duuk_admin_notice(a,'Aviso administrativo isolado','Teste de reenvio',eid);
 perform public.duuk_admin_notice(a,'Aviso administrativo isolado','Teste de reenvio',eid);
 if (select count(*) from public.duuk_notifications where user_id=a and dedupe_key='notice:'||a||':'||eid)<>1 then raise exception 'Administrative notice retry duplicated';end if;
 update public.duuk_profiles set is_super_admin=false where id=a;
 create temporary table test_duuk_content(key text,content jsonb,version bigint);
 create trigger test_project_notification after update on test_duuk_content for each row execute function duuk_private.project_action_notification();
 insert into test_duuk_content values('draft','{"projects":[]}',1);
 update test_duuk_content set content=jsonb_build_object('projects',jsonb_build_array(jsonb_build_object('id','test-project-'||a,'title','Projeto de teste','status','draft'))),version=2;
 if not exists(select 1 from public.duuk_notifications where user_id=b and category='projects' and dedupe_key='project:new:test-project-'||a) then raise exception 'New project notification missing';end if;
 update test_duuk_content set content=jsonb_set(content,'{projects,0,status}','"published"'),version=3;
 if not exists(select 1 from public.duuk_notifications where user_id=b and category='projects' and title='Visibilidade do projeto alterada') then raise exception 'Project visibility notification missing';end if;
 perform set_config('duuk.test.a',a::text,true);
end $$;
set local role authenticated;
do $$ begin
 if exists(select 1 from public.duuk_notifications where user_id<>auth.uid()) then raise exception 'Notifications crossed accounts through RLS';end if;
 update public.duuk_notifications set read_at=now() where user_id=auth.uid();
 if exists(select 1 from public.duuk_notifications where read_at is null) then raise exception 'Mark all as read failed';end if;
 insert into public.duuk_notification_preferences(user_id,projects) values(auth.uid(),false) on conflict(user_id) do update set projects=false;
 begin perform public.duuk_calendar_backend('status',jsonb_build_object('user_id',auth.uid()));raise exception 'Browser called server RPC';exception when insufficient_privilege then null;end;
 begin perform count(*) from public.duuk_calendar_connections;raise exception 'Browser read integration table';exception when insufficient_privilege then null;end;
end $$;
reset role;
rollback;
select 'PASS: OAuth ownership/replay, future backfill, multiple accounts, queue revision/lease/retry, disconnect, deletion, notifications and server-only credentials' as result;
