-- Fixtures, histories and notifications are rolled back. No external messages or pushes.
begin;
do $$
declare actor uuid:=gen_random_uuid(); denied uuid:=gen_random_uuid(); limited uuid:=gen_random_uuid();
 role_full uuid:=gen_random_uuid(); role_none uuid:=gen_random_uuid(); role_contacts uuid:=gen_random_uuid();
 cid uuid:=gen_random_uuid(); aid uuid:=gen_random_uuid(); failed_id uuid:=gen_random_uuid(); fid uuid; revision bigint;
 model_id uuid; result jsonb; previous_count bigint; reference_at timestamptz:=((now() at time zone 'America/Sao_Paulo')::date+time '09:00') at time zone 'America/Sao_Paulo';
begin
 insert into public.duuk_roles(id,name) values(role_full,'Teste WhatsApp '||role_full),(role_none,'Teste sem CRM '||role_none),(role_contacts,'Teste contatos '||role_contacts);
 insert into public.duuk_role_permissions(role_id,permission,allowed) select role_full,key,true from public.duuk_permission_keys where key in ('crm','crm.clients','crm.activities','crm.pipeline','crm.followups');
 insert into public.duuk_role_permissions(role_id,permission,allowed) values(role_contacts,'crm',true),(role_contacts,'crm.activities',true);
 insert into auth.users(id,email) values(actor,actor||'@test.invalid'),(denied,denied||'@test.invalid'),(limited,limited||'@test.invalid');
 insert into public.duuk_profiles(id,name,email,role_id) values(actor,'Teste WhatsApp',actor||'@test.invalid',role_full),(denied,'Teste negado',denied||'@test.invalid',role_none),(limited,'Teste contato restrito',limited||'@test.invalid',role_contacts);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 insert into public.duuk_clients(name,phone,owner_id,project_name,event_date) values('Fixture WhatsApp','(11) 99999-9999',actor,'Filme de teste',current_date+5) returning id,version into cid,revision;
 if (select phone from public.duuk_clients where id=cid)<>'+5511999999999' then raise exception 'Phone not normalized';end if;
 begin update public.duuk_clients set whatsapp='javascript:5511999999999' where id=cid;raise exception 'Unsafe phone accepted';exception when sqlstate 'PT400' then null;end;
 insert into public.duuk_whatsapp_templates(title,body) values('Fixture editável','Olá {nome_cliente}') returning id into model_id;
 update public.duuk_whatsapp_templates set body='Olá {nome_cliente}, {nome_empresa}' where id=model_id and version=1;
 if (select version from public.duuk_whatsapp_templates where id=model_id)<>2 then raise exception 'Template revision missing';end if;
 result:=public.duuk_record_contact(cid,revision,aid,now(),'whatsapp','Conversa registrada manualmente','Interessado','Enviar proposta',now()+interval '1 day','proposal');
 if (select last_contact from public.duuk_clients where id=cid) is null or (select stage from public.duuk_clients where id=cid)<>'proposal' then raise exception 'Contact summary failed';end if;
 select id,version into fid,revision from public.duuk_follow_ups where client_id=cid and completed_at is null;
 if fid is null then raise exception 'Followup not created';end if;
 perform public.duuk_record_contact(cid,1,aid,now(),'whatsapp','Retry','Interessado','Enviar proposta',now()+interval '1 day','proposal');
 if (select count(*) from public.duuk_activities where client_id=cid)<>1 then raise exception 'Idempotency failed';end if;
 begin perform public.duuk_record_contact(cid,1,failed_id,now(),'whatsapp','Stale revision','','',null,null);raise exception 'Stale accepted';exception when sqlstate 'PT409' then null;end;
 update public.duuk_follow_ups set due_at=now()+interval '2 days' where id=fid and version=revision and completed_at is null;
 if (select version from public.duuk_follow_ups where id=fid)<>revision+1 then raise exception 'Reschedule revision failed';end if;
 if (select next_follow_up from public.duuk_clients where id=cid)<>(select due_at from public.duuk_follow_ups where id=fid) then raise exception 'Next followup not synced';end if;
 perform public.duuk_complete_followup(fid,revision+1,'Concluído',null,null);
 if (select next_follow_up from public.duuk_clients where id=cid) is not null then raise exception 'Completion left stale next contact';end if;
 select version into revision from public.duuk_clients where id=cid;
 begin perform public.duuk_record_contact(cid,revision,failed_id,now(),'whatsapp','Will roll back','','',now()+interval '3 days','invalid_stage');raise exception 'Invalid stage accepted';exception when check_violation then null;end;
 if exists(select 1 from public.duuk_activities where id=failed_id) then raise exception 'Partial contact committed';end if;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',limited,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 begin perform public.duuk_record_contact(cid,revision,gen_random_uuid(),now(),'whatsapp','Denied stage','','',null,'won');raise exception 'Pipeline permission bypass';exception when sqlstate 'PT403' then null;end;
 begin perform public.duuk_record_contact(cid,revision,gen_random_uuid(),now(),'whatsapp','Denied followup','','',now()+interval '1 day',null);raise exception 'Followup permission bypass';exception when sqlstate 'PT403' then null;end;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',denied,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if exists(select 1 from public.duuk_clients) or exists(select 1 from public.duuk_whatsapp_templates) then raise exception 'CRM data leaked';end if;
 begin insert into public.duuk_whatsapp_templates(title,body) values('Denied','Denied');raise exception 'Template permission bypass';exception when insufficient_privilege then null;end;
 begin perform public.duuk_record_contact(cid,revision,gen_random_uuid(),now(),'whatsapp','Denied','','',null,null);raise exception 'Contact permission bypass';exception when sqlstate 'PT403' then null;end;
 execute 'reset role';
 perform set_config('request.jwt.claims','{}',true);
 -- Stable contact/stage dates allow deterministic reminders and no repeated stale alerts.
 update public.duuk_clients set last_contact=reference_at-interval '8 days',stage_changed_at=reference_at-interval '8 days' where id=cid;
 insert into public.duuk_follow_ups(client_id,owner_id,due_at) values(cid,actor,reference_at+interval '1 hour'),(cid,actor,reference_at+interval '1 day');
 perform duuk_private.commercial_reminders(reference_at);
 select count(*) into previous_count from public.duuk_notifications where user_id=actor;
 perform duuk_private.commercial_reminders(reference_at);
 if (select count(*) from public.duuk_notifications where user_id=actor)<>previous_count then raise exception 'Duplicate reminders';end if;
 if not exists(select 1 from public.duuk_notifications where user_id=actor and dedupe_key='commercial:today:'||(reference_at at time zone 'America/Sao_Paulo')::date and title='Você tem 1 cliente para contatar hoje') then raise exception 'Daily count missing';end if;
 if not exists(select 1 from public.duuk_notifications where user_id=actor and dedupe_key like 'commercial:tomorrow:%') or not exists(select 1 from public.duuk_notifications where user_id=actor and dedupe_key like 'commercial:proposal:%') or not exists(select 1 from public.duuk_notifications where user_id=actor and dedupe_key like 'commercial:stale:%') then raise exception 'Reminder missing';end if;
 if exists(select 1 from public.duuk_notifications where user_id=denied) then raise exception 'Notification permission leaked';end if;
 if has_function_privilege('anon','public.duuk_record_contact(uuid,bigint,uuid,timestamptz,text,text,text,text,timestamptz,text)','execute') or has_function_privilege('authenticated','duuk_private.commercial_reminders(timestamptz)','execute') then raise exception 'RPC grant leaked';end if;
end $$;
rollback;
