import { useCallback } from 'react'
import { Link } from 'react-router-dom'
import { Icon } from '../admin/components'
import { listContracts, listExpenses, listMetrics } from './api'
import { brl, contractStatuses, dateLabel, expenseTotals, metricSummary, today } from './model'
import { useQuery } from './useQuery'

export default function DashboardPage() {
  const query=useCallback(async()=>{const [contracts,expenses,metrics]=await Promise.all([listContracts(),listExpenses(today().slice(0,7)),listMetrics(30)]);return {contracts,expenses,metrics}},[])
  const {data,error,reload:load}=useQuery(query)
  const totals=expenseTotals(data?.expenses||[]),metrics=metricSummary(data?.metrics||[]),pending=(data?.contracts||[]).filter(c=>['pending','partial'].includes(c.status))
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">DUUK / VISÃO GERAL</p><h1>Seu próximo capítulo<span>.</span></h1><p>O site, os contratos e as contas em um só lugar.</p></div><button className="admin-button admin-button--secondary" onClick={load}>Atualizar</button></div>{error&&<p className="admin-error" role="alert">{error}</p>}<div className="admin-stats office-money-stats"><div><span>Despesas deste mês</span><strong>{data?brl(totals.total):'…'}</strong></div><div><span>Contratos aguardando assinatura</span><strong>{data?pending.length:'…'}</strong></div><div><span>Páginas vistas · 30 dias</span><strong>{data?metrics.view.toLocaleString('pt-BR'):'…'}</strong></div></div><div className="office-shortcuts">{[['document','Contratos','Subir PDF e preparar assinaturas','/admin/contratos'],['wallet','Despesas','Registrar e acompanhar pagamentos','/admin/despesas'],['chart','Insights','Entender os acessos ao site','/admin/insights'],['film','Portfólio','Editar projetos, capas e vídeos','/admin/portfolio']].map(([icon,title,subtitle,path])=><Link className="admin-panel office-shortcut" to={path} key={path}><Icon name={icon} size={24} /><div><h2>{title}</h2><p>{subtitle}</p></div><Icon name="arrow" /></Link>)}</div><div className="office-grid"><section className="admin-panel office-panel"><div className="office-section-title"><h2>Contratos em andamento</h2><Link className="admin-text-button" to="/admin/contratos">Ver todos ↗</Link></div>{pending.length?pending.slice(0,5).map(c=><Link className="office-mini-row" to={`/admin/contratos/${c.id}`} key={c.id}><div><strong>{c.title}</strong><small>{c.client_name}</small></div><span className="office-badge is-pending">{contractStatuses[c.status]}</span></Link>):<p className="office-muted">Nenhum contrato aguardando assinatura.</p>}</section><section className="admin-panel office-panel"><div className="office-section-title"><h2>Despesas a pagar no mês</h2><Link className="admin-text-button" to="/admin/despesas">Ver despesas ↗</Link></div>{data?.expenses.some(e=>e.status==='pending')?data.expenses.filter(e=>e.status==='pending').slice(0,5).map(e=><div className="office-mini-row" key={e.id}><div><strong>{e.title}</strong><small>Vence em {dateLabel(e.due_date)}</small></div><strong>{brl(e.amount_cents)}</strong></div>):<p className="office-muted">Nenhuma despesa pendente neste mês.</p>}</section></div></>
}
