import { useCallback, useState } from 'react'
import { listMetrics } from './api'
import { metricSummary } from './model'
import { RefreshButton } from '../admin/components'
import { useQuery } from './useQuery'

const group=(records,key)=>Object.entries(records.reduce((out,r)=>({...out,[r[key]]:(out[r[key]]||0)+Number(r.count)}),{})).sort((a,b)=>b[1]-a[1])
function BarList({rows,labels={}}) { const max=Math.max(...rows.map(r=>r[1]),1);return rows.length?<div className="office-bars">{rows.map(([label,value])=><div key={label}><span>{labels[label]||label}</span><strong>{value.toLocaleString('pt-BR')}</strong><i style={{width:`${value/max*100}%`}} /></div>)}</div>:<p className="office-muted">Os dados aparecerão após as primeiras visitas.</p> }

export default function InsightsPage() {
  const [days,setDays]=useState(30)
  const query=useCallback(()=>listMetrics(days),[days])
  const {data,loading,error,reload:load}=useQuery(query)
  const records=data||[]
  const totals=metricSummary(records),views=records.filter(r=>r.event==='view'),timeline=group(views,'day').sort((a,b)=>a[0].localeCompare(b[0])),max=Math.max(...timeline.map(r=>r[1]),1)
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">ADMINISTRATIVO / SITE</p><h1>Insights<span>.</span></h1><p>Como as pessoas encontram e exploram a DUUK.</p></div><select className="office-select" aria-label="Período dos insights" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Últimos 7 dias</option><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 90 dias</option></select></div>{error&&<p className="admin-error" role="alert">{error} <button onClick={load}>Tentar novamente</button></p>}<div className="admin-stats"><div><span>Visualizações de páginas</span><strong>{loading&&!data?'…':totals.view.toLocaleString('pt-BR')}</strong></div><div><span>Aberturas de filmes</span><strong>{loading&&!data?'…':totals.play.toLocaleString('pt-BR')}</strong></div><div><span>Cliques de contato</span><strong>{loading&&!data?'…':totals.contact.toLocaleString('pt-BR')}</strong></div></div><section className="admin-panel office-panel"><div className="office-section-title"><h2>Visitas por dia</h2><RefreshButton onRefresh={load}/></div>{timeline.length?<div className="office-timeline" role="img" aria-label={timeline.map(([day,value])=>`${day}: ${value} visualizações`).join('; ')}>{timeline.map(([day,value])=><div key={day} title={`${day}: ${value}`}><i style={{height:`${Math.max(4,value/max*100)}%`}} /><span>{day.slice(8)}</span></div>)}</div>:<p className="office-empty">A coleta começa com esta atualização. Ainda não há histórico neste período.</p>}</section><div className="office-grid"><section className="admin-panel office-panel"><h2>Páginas mais vistas</h2><BarList rows={group(views,'page').slice(0,8)} labels={{'/':'Página inicial','/portfolio':'Portfólio','/sobre':'Sobre','/contato':'Contato'}} /></section><section className="admin-panel office-panel"><h2>Origem das visitas</h2><BarList rows={group(views,'source')} /></section><section className="admin-panel office-panel"><h2>Dispositivos</h2><BarList rows={group(views,'device')} labels={{mobile:'Celular',desktop:'Computador'}} /></section><section className="admin-panel office-panel"><h2>Sobre os números</h2><p className="office-muted">Visualizações contam páginas abertas, não pessoas únicas. Aberturas de filmes contam cliques no player. Cliques de contato incluem e-mail, WhatsApp e o formulário.</p><p className="office-muted">Dados agregados, sem cookies de análise ou identificação individual de visitantes. O painel, as assinaturas e acessos com a conta administrativa não entram na coleta. Bloqueadores podem reduzir a contagem.</p></section></div></>
}
