import { strToU8, zipSync } from 'fflate'
import { expenseCategories, expenseTotals } from './model.js'
import { monthLabel } from './calendarModel.js'

// XML 1.0 prohibits these characters even when entered in a text field.
// eslint-disable-next-line no-control-regex
const xml = value => String(value??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')
const dateSerial = date => Math.round((Date.parse(`${date}T00:00:00Z`)-Date.UTC(1899,11,30))/86400000)
const textCell = (value,style=0) => ({value,style})
const numberCell = (value,style=2) => ({value:Number(value),style,numeric:true})
const dayCell = value => value?numberCell(dateSerial(value),3):textCell('')
function sheet(rows,widths) {
 const content=rows.map((row,index)=>`<row r="${index+1}"${index===0?' ht="28" customHeight="1"':''}>${row.map((cell,column)=>{const ref=String.fromCharCode(65+column)+(index+1);return cell.numeric?`<c r="${ref}" s="${cell.style}"><v>${cell.value}</v></c>`:`<c r="${ref}" s="${cell.style}" t="inlineStr"><is><t xml:space="preserve">${xml(cell.value)}</t></is></c>`}).join('')}</row>`).join('')
 return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${String.fromCharCode(64+widths.length)}${rows.length}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths.map((width,i)=>`<col min="${i+1}" max="${i+1}" width="${width}" customWidth="1"/>`).join('')}</cols><sheetData>${content}</sheetData><autoFilter ref="A1:${String.fromCharCode(64+widths.length)}${rows.length}"/></worksheet>`
}
export function expensesWorkbook(records,month,filter='all') {
 const totals=expenseTotals(records)
 const rows=[['Despesa','Categoria','Valor (R$)','Vencimento','Status','Pagamento','Descrição'].map(value=>textCell(value,1)),...records.map(r=>[textCell(r.title),textCell(expenseCategories[r.category]),numberCell(Number(r.amount_cents)/100),dayCell(r.due_date),textCell(r.status==='paid'?'Pago':'A pagar'),dayCell(r.paid_date),textCell(r.description)])]
 const summary=[['DUUK / Resumo financeiro','Valor'].map(value=>textCell(value,1)),[textCell('Período'),textCell(monthLabel(month))],[textCell('Filtro'),textCell({all:'Todas as despesas',paid:'Pagas',pending:'A pagar'}[filter])],[textCell('Quantidade de despesas'),numberCell(records.length,0)],[textCell('Total (R$)'),numberCell(totals.total/100)],[textCell('Pago (R$)'),numberCell(totals.paid/100)],[textCell('A pagar (R$)'),numberCell(totals.pending/100)]]
 const files={
 '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Despesas" sheetId="1" r:id="rId1"/><sheet name="Resumo" sheetId="2" r:id="rId2"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="&quot;R$&quot; #,##0.00"/><numFmt numFmtId="165" formatCode="dd/mm/yyyy"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFF8F3"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF080808"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
 'xl/worksheets/sheet1.xml':sheet(rows,[38,26,19,17,15,17,60]),
 'xl/worksheets/sheet2.xml':sheet(summary,[36,32])
 }
 return zipSync(Object.fromEntries(Object.entries(files).map(([path,content])=>[path,strToU8(content)])),{level:6})
}
